### PR TITLE
defuck

### PR DESCRIPTION
**Pull request by besser435**
Made the code a bit neater

### CODE REVIEW

**Comment by AutisticAndAshamed** [comment]
The main thing that needs to be defucked is the integral itself. It should probably be vel_0 plus the additional velocity shit, but idk if that would fix the problem

**Comment by besser435** [comment]
> The main thing that needs to be defucked is the integral itself. It should probably be vel_0 plus the additional velocity shit, but idk if that would fix the problem
> 
> Also, ignore the thing that determines which direction is up. It's a good concept, but I have no idea how the fuck it's supposed to work, and it would probably be best to remove it for now

bi

**Comment by AutisticAndAshamed** [comment]
Fuck you

**Comment by besser435** [comment]
> Fuck you
> 

Fuck you

**Pull request merged**
